### ISSUE TITLE
Open tab only if none is open

### ISSUE THREAD

**Issue by Alex293** [sindresorhus/github-notifier-safari#11]
Hi, The indicator is great but when you click on it, it always open a new tab. That be nice if it could check if there is already a notification tab and just select this one.

Is this repo still maintained (last commit a year ago) ?

**Comment by sindresorhus** [comment]
It used to do that, but there was some Safari issues. See: https://github.com/sindresorhus/notifier-for-github-safari/pull/5#r56747724

> Is this repo still maintained (last commit a year ago) ?

It's maintained, just not actively worked on, as I don't use this extension anymore, but happy to review PRs.

**Comment by Alex293** [comment]
Thanks for you quick reply. I was thinking about iterating on open tab and if there a notification tap select it and if not open a new tab. Would be the intersection of the old and new behaviour.

**Comment by Haroenv** [comment]
relevant code is here: https://github.com/sindresorhus/notifier-for-github-safari/blob/master/Notifier%20for%20GitHub.safariextension/main.js#L31-L33

**Comment by sindresorhus** [comment]
Apple has deprecated JS-based Safari extensions, so I'm deprecating this project.
