### ISSUE TITLE
Display desktop notifications

### ISSUE THREAD

**Issue by Haroenv** [sindresorhus/github-notifier-safari#7]
Related: https://github.com/sindresorhus/notifier-for-github-chrome/issues/12

**Comment by Haroenv** [comment]
Since the extension currently only gets the number of notifications, it'll be needed to switch to the notifications api, like on the chrome version.

**Comment by sindresorhus** [comment]
Apple has deprecated JS-based Safari extensions, so I'm deprecating this project.
