### ISSUE TITLE
Support for GitHub Enterprise?

### ISSUE THREAD

**Issue by mekhanique** [sindresorhus/github-notifier-safari#8]
It would be great if those who use a github enterprise instance could point this plugin both internally (at their enterprise instance) and externally (at github.com).  This should be a relatively easy change as it's basically just allowing the user to specify a different API end point.   

Would love to make a PR here, but I'm prohibited by my employer from doing so.  

Thanks!

**Comment by Haroenv** [comment]
Right now this repo didn't use the api yet, as the Chrome extension does. We'll take a look at making both extensions work in the same way.

**Comment by sindresorhus** [comment]
Apple has deprecated JS-based Safari extensions, so I'm deprecating this project.
