### ISSUE TITLE
Notifier count is cut off

### ISSUE THREAD

**Issue by sfhosley** [sindresorhus/github-notifier-safari#9]
The right side of the notification badge is cut off.

<img width="54" alt="github-notifier" src="https://cloud.githubusercontent.com/assets/5246930/19441117/1c433e64-944a-11e6-8b6c-46d1f14d7d17.png">

**Comment by sindresorhus** [comment]
That's a Safari bug and should be reported to Apple. This extension is just using the toolbar icon badge API to set the count.
